FROM node:14-alpine

ENV NODE_ENV production

WORKDIR /app
COPY package.json .
COPY .next/ .next/
COPY .env .
# COPY .env.local . # TODO
COPY next.config.js .
COPY node_modules/ node_modules/

EXPOSE 3000
CMD npm run start:next