apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-veiviser
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 80
  accessPolicy:
    outbound:
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
      rules: []
  ingresses:
{{#each ingresses}}
   - "{{this}}"
{{/each}}
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /prometheus
  liveness:
    path: /sosialhjelp/isAlive
    initialDelay: 20
  readiness:
    path: /sosialhjelp/isReady
    initialDelay: 20
  resources:
    limits:
      cpu: 300m
      memory: 128Mi
    requests:
      cpu: 40m
      memory: 64Mi
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 70
  webproxy: {{webProxyEnabled}}
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
