apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 5000
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: api.sanity.io
        - host: hvfvg2j3.api.sanity.io
        - host: apicdn.sanity.io
        - host: hvfvg2j3.apicdn.sanity.io
        - host: cdn.sanity.io
      rules: []
  ingresses:
{{#each ingresses}}
   - "{{this}}"
{{/each}}
  liveness:
    path: /sosialhjelp/api/isAlive
    initialDelay: 20
  readiness:
    path: /sosialhjelp/api/isReady
    initialDelay: 20
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 70
  webproxy: {{webProxyEnabled}} 
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
