apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-veiviser-sanity
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /sosialhjelp/studio/internal/api/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/studio/internal/api/isReady
    initialDelay: 5
    timeout: 1
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  ingresses:
    - https://www.nav.no/sosialhjelp/studio
