name: Nattlig restart
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  deploy_dev-gcp:
    uses: navikt/sosialhjelp-veiviser-ny/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: dev-gcp
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
  deploy_dev-gcp-mock:
    uses: navikt/sosialhjelp-veiviser-ny/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: dev-gcp-mock
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
  deploy-sanity_dev-gcp:
    uses: navikt/sosialhjelp-veiviser-ny/.github/workflows/build_and_deploy_sanity_dev.yml@main
    with:
      config-file-name: dev-gcp
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}